[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "circuit-knitting-toolbox"
version = "0.0.0"
description = "A software prototype for a circuit knitting toolbox which connects user applications with runtime primitives"
readme = "README.md"
license = {file = "LICENSE.txt"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Physics",
]

requires-python = ">=3.7"

dependencies = [
    "qiskit-aer>=0.11.0",
    "qiskit-terra>=0.22.0",
    "qiskit-nature>=0.4.4",
    "qiskit-ibm-runtime>=0.7.0",
    "qiskit-ibmq-provider>=0.19.2",
    "nptyping>=2.1.1",
    "docplex>=2.23.222",
    "cplex>=22.1.0.0; platform_machine != 'arm64'",
]

[project.optional-dependencies]
dev = [
    "black[jupyter]==22.10.0",
    "mypy==0.982",
    "pytest>=6.2.5",
    "pydocstyle",
    "pytest-randomly>=1.2.0",
    "nbmake"
]
test = [
    "pyscf>=2.0.1; sys_platform != 'win32'",
    "pytest>=6.2.5",
    "pytest-randomly>=1.2.0",
]
notebook-dependencies = [
    "quantum-serverless>=0.0.1",
    "pyscf>=2.0.1; sys_platform != 'win32'",
    "matplotlib",
    "ipywidgets",
    "pylatexenc",
]

[tool.autoflake]
remove-unused-variables = true
remove-all-unused-imports = true

[tool.flit.module]
name = "circuit_knitting_toolbox"
